### PR TITLE
Rolling doubles

### PR DESCRIPTION
**Pull request by Jexc0de**
Added Doubles, and sending the player to jail on the third double. Turned wiping the bottom of the screen into a callable function.

### CODE REVIEW

**Review by adamgulde — CHANGES_REQUESTED** [review]
This is a very straightforward approach. I like it but please make the repeated code into its own callable function. It'd be very bloated to have 150+ lines that are identical.  @Jexc0de

**Comment by Jexc0de** [comment]
Yeah, I was thinking about doing that, I'll get right on it.

**Review by adamgulde — CHANGES_REQUESTED** [review]
Good work on commenting code, very helpful. Some feedback:
- [CODE STYLE] I think it would be better practice if instead of using two booleans to store the roll amount, you used a number. Maybe call it "num_rolls." This would simplify some of your if statements. 
- [CODE STYLE] In the main game loop [the while(True) loop], the logic could be a bit simpler. Maybe calling PlayerRoll recursively within PlayerRoll if the player has doubles and num_rolls < 3 would simplify this, and it would stay within the PlayerRoll function. This has the added benefit of not needing to return anything from PlayerRoll. 
- Also on the if statements (around lines 643-656), you are repeating "refresh_board"s. Because you're always going to refresh the board, simply move that outside of the conditionals.
- [VISUAL] for third double, history text should be "(player) rolled doubles three times in a row." player is going to jail is good 
-  [CODE STYLE] please use consistent variable naming styles. lowercase_snake_case is common in python. See: PlayerRoll(), Roll(), BottomScreenWipe(), and any other instances of UpperCamelCase typing. Note that UpperCamelCase is used typically for class names. 
- [CODE STYLE] rename Die tuple (returned from Roll() to dice, as it represents 2 die(s) 
- [BUG] player gets **perpetually** stuck in jail if they roll doubles thrice OR get sent to jail by Go To Jail (location 30). technically fixing jail isn't part of THIS issue, but since you claimed it you could merge it to this pr. I say this because jail is very closely related to doubles so it makes sense to fix both, and currently gameplay *stops* for many players when they are sent to jail now

I know this is a lot of feedback so please message me on Discord if you need any clarification or if you want to explain why you coded a certain way. I could definitely be wrong.

**Review by adamgulde — APPROVED** [review]
lgtm!

**Pull request merged**
